# Generated by Django 4.0.6 on 2022-07-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_phone_slug_alter_phone_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
