# Generated by Django 4.0.6 on 2022-07-21 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_type_color'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='companyprofile',
            table='companyprofile',
        ),
        migrations.AlterModelTable(
            name='type',
            table='type',
        ),
    ]
