# Generated by Django 4.0.6 on 2022-07-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_companyprofile_table_alter_type_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='best_selling',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='latest',
            field=models.BooleanField(default=True),
        ),
    ]
